routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('email', function(){
	return new App\Mail\LoginCredentials(App\User::first());
});

Route::get('/', 'PagesController@Home')->name('home');
Route::get('pagina/{pagina}','PagesController@showPage')->name('page.single');
Route::get('/blog/{post}', 'PostsController@show')->name('blog.single');
Route::get('/categoria/{category}', 'CategoriesController@show')->name('categories.show');
Route::get('/tag/{tag}', 'TagsController@show')->name('tags.show');
Route::post('/busqueda', 'SearchController@show')->name('search.show');
Route::post('/comments', 'CommentsController@store')->name('comments.store');



Route::group([
	'prefix' => 'admin', 
	'namespace' => 'Admin', 
	'middleware' => 'auth'],
	 function(){
	Route::get('/', 'AdminController@index')->name('admin.dashboard');

	Route::resource('posts', 'PostsController', [
		'as' => 'admin', 
		'except' => 'show'
	]);

	Route::resource('users', 'UsersController', ['as' => 'admin']);
	Route::resource('categories', 'CategoriesController', [
		'as' => 'admin', 
		'except' => 'show'
	]);
	Route::resource('tags', 'TagsController', [
		'as' => 'admin', 
		'except' => 'show'
	]);

	Route::middleware('role:Admin')
			->resource('pages', 'PagesController', [
				'as' => 'admin',
				'except' => 'show',
			]);

	Route::middleware('role:Admin')
			->resource('comments', 'CommentsController', 
				['as' => 'admin', 
				'except' => ['show', 'create', 'store']
			    ]
			);

	Route::middleware('role:Admin')
			->resource('responses', 'ResponsesController', 
				['as' => 'admin', 
				'except' => ['index', 'show', 'create', 'store']
				]
			);



	Route::middleware('role:Admin')
			->patch('comments/{comment}/approve', 'CommentsController@approve')
			->name('admin.comments.approve');

	Route::middleware('role:Admin')
			->patch('comments/{comment}/disapprove', 'CommentsController@disapprove')
			->name('admin.comments.disapprove');

	Route::middleware('role:Admin')
			->patch('responses/{response}/approve', 'ResponsesController@approve')
			->name('admin.responses.approve');

	Route::middleware('role:Admin')
			->patch('responses/{response}/disapprove', 'ResponsesController@disapprove')
			->name('admin.responses.disapprove');
	
	Route::middleware('role:Admin')
	        ->put('/users/{user}/roles', 'UsersRolesController@update')
	        ->name('admin.users.roles.update');

	Route::middleware('role:Admin')
	        ->put('/users/{user}/permissions', 'UsersPermissionsController@update')
	        ->name('admin.users.permissions.update');

/*	Route::middleware('role:Admin')
			->resource('roles', 'RolesController', ['as' => 'admin', 'except' => 'show']);

	Route::middleware('role:Admin')
			->resource('permissions', 'PermissionsController', ['as' => 'admin', 'except' => 'show']);*/		
	
	Route::resource('photos', 'PhotosController', ['as' => 'admin']);
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');


Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

Route::get('confirmation/{id}/{email}', 'Auth\RegisterController@confirmation')->name('account.confirmation');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Post.php
<?php

namespace App;

use App\Traits\CommonInModels;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{

    use CommonInModels;

    protected $dates = ['published_at'];

    protected $fillable = [
       'title', 'excerpt', 'body', 'published_at', 'category_id', 'user_id', 
    ];

    public function category($value= ""){
    	return $this->belongsTo(Category::class);
    }

    public function tags(){
    	return $this->belongsToMany(Tag::class);
    }

    public function comments(){
        return $this->hasMany(Comment::class);
    }

    public function photos(){
        return $this->hasMany(Photo::class);
    }

    public function owner(){
        return $this->belongsTo(User::class, 'user_id');
    }


    public function scopePublished($query){
    	$query->whereNotNull('published_at')
     		  ->where('published_at', '<=', Carbon::now())
              ->orderBy('id', 'desc');
    }

    public function scopeAllowed($query){
        return auth()->user()->can('view', $this) 
                  ? $query 
                  : $query->where('user_id', auth()->user()->id);
    }

 

    public function setPublishedAtAttribute($published_at){
        $this->attributes['published_at'] = $published_at ? Carbon::parse($published_at) : null;
    }

    public function setCategoryIdAttribute($category){
        $this->attributes['category_id'] = Category::find($category) 
                                            ? $category 
                                            : Category::create(['name' => $category])->id; 
    }

    public function storeTags($tags, $method = 'sync'){
      
      $tagsIds = collect($tags)->map(function($tag){
         return Tag::find($tag) ? $tag : Tag::create(['name' => $tag])->id;
      }); 

       return $this->tags()->$method($tagsIds);        
    }

    protected static function boot(){
        parent::boot();

        static::deleting(function($post){
           $post->tags()->detach();
           $post->photos->each->delete();
        });
    }

    public function isPublished(){
        return ! is_null($this->published_at) && $this->published_at < today();
    }

    public function storePhotos($request, $post){
       if($request->has('thumbnail')){
            $post->photos()->create([
               'url' => Storage::url($request->file('thumbnail')->store('posts', 'public')),
            ]);
        }
    }



}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\StorePostRequest;
use App\Photo;
use App\Post;
use App\Tag;
use Carbon\Carbon;
use Illuminate\Http\Request;


class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::allowed()->get();
        return view('admin.posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', new Post);
        
        return view('admin.posts.create', [
            'title' => "Crear una publicación",
            'categories' => Category::all(),
            'tags' => Tag::all(),
            'images' => Photo::all(),

        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostRequest $request)
    { 
       $request['user_id'] = auth()->user()->id;
       $post = Post::create($request->all());
       $post->storeTags($request->get('tags'), 'attach');

       $post->storePhotos($request, $post);

       return redirect(route('admin.posts.edit', $post))->withFlash('Tu publicación ha sido creada correctamente');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $this->authorize('update', $post);
        return view('admin.posts.edit', [
            'title' => 'Editando la publicación "' . $post->title . '"',
            'post' => $post,
            'categories' => Category::all(),
            'tags' => Tag::all(),
            'images' => Photo::all(),

        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StorePostRequest $request, Post $post)
    {
       $this->authorize('update', $post);

       $post->update($request->all());

       $post->storeTags($request->get('tags'), 'sync');

       $post->storePhotos($request, $post);

       return redirect(route('admin.posts.edit', $post))->withFlash('Tu publicación ha sido actualizada correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $this->authorize('delete', $post);

        $post->delete();

        return back()->withFlash('La publicación ha sido eliminada correctamente');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Comment;
use App\Post;
use App\Response;
use App\Tag;
use Illuminate\Http\Request;

class PostsController extends Controller
{
    public function show(Post $post){

    	if($post->isPublished() || auth()->check()){
	    	return view('posts.single', [
	    		'title' => $post->title,
	    		'post' => $post,
	    		'populars' => Post::lastFive()->get(),
	    		'comments' => $comments = Comment::isApproved($post)->get(),
	    		'categories' => Category::all(),
	    		'tags' => Tag::all(),
	    	]);
        }

       abort(404, 'Pagina no encontrada');
    }


}

resources/views/admin/posts/partials/modal-images.blade.php
<div class="modal" id="modal-images">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Biblioteca de imágenes</h4>
      </div>
      <div class="modal-body">
        <div class="row">
        <div class="col-md-12">
          <!-- Custom Tabs -->
          <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#tab_1" data-toggle="tab">Desde la biblioteca</a></li>
              <li><a href="#tab_2" data-toggle="tab">Subir imagen</a></li>
              <li><a href="#tab_3" data-toggle="tab">Tab 3</a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="tab_1">
                Biblioteca de imágenes
                <div class="row" style="padding: 19px;" id="imagesServer">
                    @foreach ($images as $image)
                      <div class="col-xs-3">
                        <img src="{{ url($image->url) }}" class="img-responsive" style="width: 100px; height: 100px; padding: 6px;">
                      </div>
                    @endforeach
                </div>

              </div>
              <!-- /.tab-pane -->
              <div class="tab-pane" id="tab_2">

                <p>Subir imágenes</p>
                <br>
                <br>
                <div class="dropzone">
                  
                </div>
              </div>
              <!-- /.tab-pane -->
              <div class="tab-pane" id="tab_3">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                It has survived not only five centuries, but also the leap into electronic typesetting,
                remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset
                sheets containing Lorem Ipsum passages, and more recently with desktop publishing software
                like Aldus PageMaker including versions of Lorem Ipsum.
              </div>
              <!-- /.tab-pane -->
            </div>
            <!-- /.tab-content -->
          </div>
          <!-- nav-tabs-custom -->
        </div>
        <!-- /.col -->
      </div>
     </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
        <!-- /.modal -->

@push('scripts')
<script>
  $('#modal-images').modal({
    'backdrop': false,
    'show': false,
  });

   var myDropzone = new Dropzone('.dropzone', {
      url: "{{ route('admin.photos.store') }}",
      acceptedFiles: 'image/*',
      paramName: 'images',
      headers: {
        'X-CSRF-TOKEN': '{{ csrf_token() }}'
      },
      dictDefaultMessage: "Arrastra o selecciona las imágenes",
    });

    myDropzone.on('error', function(file, res){
      var msg = res.errors.images[0];
      $('.dz-error-message:last > span').text(msg);
    });

    myDropzone.on('success', function(file, res){
      var html = '<div class="col-xs-3"> <img src="' + res + '" class="img-responsive" style="width: 100px; height: 100px; padding: 6px;"> </div>';
      var img = '<img src=" '+ res +' " >';
      var editor = $('#editor');
      alert(editor[0].val());
      $('#imagesServer').append(html);

    });

    Dropzone.autoDiscover = false;
  
</script>
@endpush