routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('email', function(){
	return new App\Mail\LoginCredentials(App\User::first());
});

Route::get('/', 'PagesController@Home')->name('home');
Route::get('pagina/{pagina}','PagesController@showPage')->name('page.single');
Route::get('/blog/{post}', 'PostsController@show')->name('blog.single');
Route::get('/categoria/{category}', 'CategoriesController@show')->name('categories.show');
Route::get('/tag/{tag}', 'TagsController@show')->name('tags.show');
Route::post('/busqueda', 'SearchController@show')->name('search.show');
Route::post('/comments', 'CommentsController@store')->name('comments.store');



Route::group([
	'prefix' => 'admin', 
	'namespace' => 'Admin', 
	'middleware' => 'auth'],
	 function(){
	Route::get('/', 'AdminController@index')->name('admin.dashboard');

	Route::resource('posts', 'PostsController', [
		'as' => 'admin', 
		'except' => 'show'
	]);

	Route::resource('users', 'UsersController', ['as' => 'admin']);
	Route::resource('categories', 'CategoriesController', [
		'as' => 'admin', 
		'except' => 'show'
	]);
	Route::resource('tags', 'TagsController', [
		'as' => 'admin', 
		'except' => 'show'
	]);

	Route::middleware('role:Admin')
			->resource('pages', 'PagesController', [
				'as' => 'admin',
				'except' => 'show',
			]);

	Route::middleware('role:Admin')
			->resource('comments', 'CommentsController', 
				['as' => 'admin', 
				'except' => ['show', 'create', 'store']
			    ]
			);

	Route::middleware('role:Admin')
			->resource('responses', 'ResponsesController', 
				['as' => 'admin', 
				'except' => ['index', 'show', 'create', 'store']
				]
			);



	Route::middleware('role:Admin')
			->patch('comments/{comment}/approve', 'CommentsController@approve')
			->name('admin.comments.approve');

	Route::middleware('role:Admin')
			->patch('comments/{comment}/disapprove', 'CommentsController@disapprove')
			->name('admin.comments.disapprove');

	Route::middleware('role:Admin')
			->patch('responses/{response}/approve', 'ResponsesController@approve')
			->name('admin.responses.approve');

	Route::middleware('role:Admin')
			->patch('responses/{response}/disapprove', 'ResponsesController@disapprove')
			->name('admin.responses.disapprove');
	
	Route::middleware('role:Admin')
	        ->put('/users/{user}/roles', 'UsersRolesController@update')
	        ->name('admin.users.roles.update');

	Route::middleware('role:Admin')
	        ->put('/users/{user}/permissions', 'UsersPermissionsController@update')
	        ->name('admin.users.permissions.update');

/*	Route::middleware('role:Admin')
			->resource('roles', 'RolesController', ['as' => 'admin', 'except' => 'show']);

	Route::middleware('role:Admin')
			->resource('permissions', 'PermissionsController', ['as' => 'admin', 'except' => 'show']);*/		
	
	Route::resource('photos', 'PhotosController', ['as' => 'admin']);
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');


Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

Route::get('confirmation/{id}/{email}', 'Auth\RegisterController@confirmation')->name('account.confirmation');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Comment.php
<?php

namespace App;

use App\Traits\CommonInModels;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use CommonInModels;

    protected $dates = ['published_at'];
    protected $guarded = [];

    public function responses(){
    	return $this->hasMany(Response::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function post(){
    	return $this->belongsTo(Post::class);
    }

    public function setPublishedAtAttribute($published_at){
    	$this->attributes['published_at'] = $published_at == null ? now() : $published_at;
    }

    public function scopeApproved($query, Post $post){
        $q = $query->where('post_id', $post->id);
       return ( auth()->check() && auth()->user()->hasRole('Admin') )
                ? $q
                : $q->where('approved', 1);
    }

    public static function isApproved(Post $post){
        return static::approved($post);
    }
    
}

app/Http/Controllers/Admin/CommentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Comment;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.comments.index', ['comments' => Comment::all()]);
    }

    public function approve(Comment $comment){
        $comment->update(['approved' => 1]);

        return back()->withFlash("Comentario aprobado correctamente.");
    }

    public function disapprove(Comment $comment){
        $comment->update(['approved' => 0]);

        return back()->withFlash("Comentario desaprobado correctamente.");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $comment)
    {
        return view('admin.comments.edit', ['comment' => $comment]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $comment)
    {
        $this->validate($request, [
            'author_name' => 'required',
            'author_email' => 'required',
            'body' => 'required',
        ]);

        $comment->update($request->all());

        return back()->withFlash('Comentario editado correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $comment->delete();

        return back()->withFlash('Comentario eliminado correctamente');
    }
}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Response;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    protected $guarded = [];

    public function store(Request $request){
    	if(request()->ajax()){
    		if($request->author_name == ''){
    			echo "El campo Nombre es obligatorio";
    			return;
    		}

    		if($request->author_email == ''){
    			echo "El campo Correo es obligatorio";
    			return;
    		}

   	        if($request->body == ''){
    			echo "Escribe un comentario";
    			return;
    		}

    		$request['approved'] = 1;

    		if($request->filled('comment_id')){
	    		Response::create($request->except('post_id'));
    		} else {
    			Comment::create($request->except('comment_id'));
    		}

    		return 'true';

    	}else {
    		return back();
    	}
    }
}

resources/views/admin/comments/edit.blade.php
@extends('admin.layouts.layout')

@section('content')
<div class="row">
	<div class="col-md-6">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">
					Editando el comentario
				</h3>
			</div>

			<div class="box-body">
				@if ($errors->any())
					<ul class="list-group">
						@foreach ($errors->all() as $error)
							<li class="list-group-item list-group-item-danger">
								{{ $error }}
							</li>
						@endforeach
					</ul>
				@endif

				@php
					$post = $comment->post;
				@endphp
				
				<form method="POST" action="{{ route('admin.comments.update', $comment) }}">
					{{ csrf_field() }} {{ method_field('PATCH') }}
					<div class="form-group {{ $errors->has('author_name') ? 'has-error' : '' }}">
						<label for="">Autor:</label>
						<input type="text" name="author_name" value="{{ old('author_name', $comment->author_name) }}" class="form-control">
					</div>

					<div class="form-group {{ $errors->has('author_email') ? 'has-error' : '' }}">
						<label for="">Email:</label>
						<input type="email" name="author_email" value="{{ old('author_email', $comment->author_email) }}" class="form-control">
					</div>

					<div class="form-group {{ $errors->has('author_url') ? 'has-error' : '' }}">
						<label for="">Url:</label>
						<input type="text" name="author_url" value="{{ old('author_url', $comment->author_url) }}" class="form-control">
					</div>

					<div class="form-group {{ $errors->has('author_name') ? 'has-error' : '' }}">
						<label for="">Comentario:</label>
						<textarea name="body" class="form-control" rows="10">{!! old('body', $comment->body) !!}</textarea>
					</div>

					<div class="form-group">
						<button class="btn btn-primary form-control">actualizar comentario</button>
					</div>
				</form>

				@if($comment->approved == 0)
					<form method="POST" action="{{ route('admin.comments.approve', $comment) }}">
						{{ csrf_field() }} {{ method_field('PATCH') }}

						<div class="form-group">
							<inp value="1">
							<button class="btn btn-success form-control">
								Aprobar
							</button>
						</div>
					</form>
				@else
					<form method="POST" action="{{ route('admin.comments.disapprove', $comment) }}">
						{{ csrf_field() }} {{ method_field('PATCH') }}

						<div class="form-group">

							<button class="btn btn-danger form-control">
								Desaprobar
							</button>
						</div>
					</form>
				@endif
			</div>
		</div>
	</div>

	@if ($comment->responses->count() > 0)
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header">
					<h3 class="box-title">Respuestas a este comentario</h3>
				</div>

				<div class="box-body">
				   <ul class="list-group">
					  @foreach ($comment->responses as $response)
						<li class="list-group-item">
							<a href="">{{ $response->author_name }}</a>

							<div class="pull-right">
								<a target="_blank" href="{{ route('blog.single', $post) . '#comment-' .$response->id  }}" class="btn btn-primary btn-xs" title="Ver">
									<i class="fa fa-eye"></i>
								</a>

								@if($response->approved == 0)
									<form method="POST" action="{{ route('admin.responses.approve', $response) }}" style="display: inline-block;">
										{{ csrf_field() }} {{ method_field('PATCH') }}			
										<button class="btn btn-success btn-xs" title="aprobar">
											<i class="fa fa-check"></i>
										</button>
									</form>
								@else
									<form method="POST" action="{{ route('admin.responses.disapprove', $response) }}" style="display: inline-block;">
										{{ csrf_field() }} {{ method_field('PATCH') }}
			
										<button class="btn btn-danger btn-xs" title="desaprobar">
											<i class="fa fa-ban"></i>
										</button>
									</form>
								@endif

								<form action="{{ route('admin.responses.destroy', $response) }}" method="POST" style="display: inline-block;">
									{{ csrf_field() }} {{ method_field('DELETE') }}
									<button onclick="return confirm('¿deseas eliminar este comentario?')" class="btn btn-danger btn-danger btn-xs" title="Eliminar">
										<i class="fa fa-remove"></i>
									</button>
								</form>								
							</div>
						</li>	
					  @endforeach
					</ul>  
				</div>
			</div>
		</div>
	@endif
</div>
@endsection

resources/views/admin/comments/index.blade.php
@extends('admin.layouts.layout')  

@section('content')   
<div class="box box-primary">
{{--     <div class="box-header">
      <h3 class="box-title">Permisos</h3>
      <a class="btn btn-primary pull-right" href="{{ route('admin.comments.create') }}">
        <i class="fa fa-plus"></i> Crear Permiso
      </a>
    </div> --}}
    <!-- /.box-header -->
    <div class="box-body">
      <table id="comments-table" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>ID</th>
          <th>Author</th>
          <th>Post</th>
          <th>Acciones</th>
        </tr>
        </thead>
		
		<tbody>
			@foreach ($comments as $comment)
        @php
          $post = $comment->post;
        @endphp
				<tr>
					<td>{{ $comment->id }}</td>
					<td>{{ $comment->author_name }}</td>
          <td>
            <a href="{{ route('blog.single', $post) }}">
              {{ $post['title'] }}
            </a>
          </td>
					<td>
            @if (!is_null($comment->approved))
              <a target="_blank" href="{{ route('blog.single', $post) . '#comment-' . $comment->id }}"
                class="btn btn-default btn-xs">
                <i class="fa fa-eye"></i>
              </a>
            @endif

						<a href="{{ route('admin.comments.edit', $comment) }}" class="btn btn-xs btn-success"><i class="fa fa-pencil"></i></a>

            <form action="{{ route('admin.comments.destroy', $comment) }}" style="display: inline" method="POST">
              {{ csrf_field() }} {{ method_field('DELETE') }}

              <button  class="btn btn-xs btn-danger"
                onclick="return confirm('¿Estás seguro que deseas eliminar esta entrada?');">
              <i class="fa fa-times"></i>
            </button>
            </form>
					</td>
				</tr>
			@endforeach
		</tbody>
      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->

  @push('styles')
  	<link rel="stylesheet" href="/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
  @endpush

  @push('scripts')
  
  	<script src="/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
	<script src="/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

     <script>
	  $(function () {
	    $('#comments-table').DataTable({
	      'paging'      : true,
	      'lengthChange': true,
	      'searching'   : true,
	      'ordering'    : true,
	      'info'        : true,
	      'autoWidth'   : false
	    })
	  })
	</script>
  @endpush

@endsection