routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('email', function(){
	return new App\Mail\LoginCredentials(App\User::first());
});

Route::get('/', 'PagesController@Home')->name('home');
Route::get('pagina/{pagina}','PagesController@showPage')->name('page.single');
Route::get('/blog/{post}', 'PostsController@show')->name('blog.single');
Route::get('/categoria/{category}', 'CategoriesController@show')->name('categories.show');
Route::get('/tag/{tag}', 'TagsController@show')->name('tags.show');
Route::post('/busqueda', 'SearchController@show')->name('search.show');
Route::post('/comments', 'CommentsController@store')->name('comments.store');



Route::group([
	'prefix' => 'admin', 
	'namespace' => 'Admin', 
	'middleware' => 'auth'],
	 function(){
	Route::get('/', 'AdminController@index')->name('admin.dashboard');

	Route::resource('posts', 'PostsController', [
		'as' => 'admin', 
		'except' => 'show'
	]);

	Route::resource('users', 'UsersController', ['as' => 'admin']);
	Route::resource('categories', 'CategoriesController', [
		'as' => 'admin', 
		'except' => 'show'
	]);
	Route::resource('tags', 'TagsController', [
		'as' => 'admin', 
		'except' => 'show'
	]);

	Route::middleware('role:Admin')
			->resource('pages', 'PagesController', [
				'as' => 'admin',
				'except' => 'show',
			]);

	Route::middleware('role:Admin')
			->resource('comments', 'CommentsController', 
				['as' => 'admin', 
				'except' => ['show', 'create', 'store']
			    ]
			);

	Route::middleware('role:Admin')
			->resource('responses', 'ResponsesController', 
				['as' => 'admin', 
				'except' => ['index', 'show', 'create', 'store']
				]
			);



	Route::middleware('role:Admin')
			->patch('comments/{comment}/approve', 'CommentsController@approve')
			->name('admin.comments.approve');

	Route::middleware('role:Admin')
			->patch('comments/{comment}/disapprove', 'CommentsController@disapprove')
			->name('admin.comments.disapprove');

	Route::middleware('role:Admin')
			->patch('responses/{response}/approve', 'ResponsesController@approve')
			->name('admin.responses.approve');

	Route::middleware('role:Admin')
			->patch('responses/{response}/disapprove', 'ResponsesController@disapprove')
			->name('admin.responses.disapprove');
	
	Route::middleware('role:Admin')
	        ->put('/users/{user}/roles', 'UsersRolesController@update')
	        ->name('admin.users.roles.update');

	Route::middleware('role:Admin')
	        ->put('/users/{user}/permissions', 'UsersPermissionsController@update')
	        ->name('admin.users.permissions.update');

/*	Route::middleware('role:Admin')
			->resource('roles', 'RolesController', ['as' => 'admin', 'except' => 'show']);

	Route::middleware('role:Admin')
			->resource('permissions', 'PermissionsController', ['as' => 'admin', 'except' => 'show']);*/		
	
	Route::resource('photos', 'PhotosController', ['as' => 'admin']);
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');


Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

Route::get('confirmation/{id}/{email}', 'Auth\RegisterController@confirmation')->name('account.confirmation');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Tag.php
<?php

namespace App;

use App\Traits\CommonInModels;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use CommonInModels;
    
    protected $guarded = [];
    

    public function posts(){
    	return $this->belongsToMany(Post::class);
    }

    public static function boot(){
    	parent::boot();

    	static::deleting(function($tag){
    		$tag->posts()->detach();
    	});
    }

}

app/Http/Controllers/Admin/TagsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.tags.index', [
            'tags' => Tag::all(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:tags',
        ]);

        Tag::create([
            'name' => $request->get('name'),
        ]);

        return back()->withFlash("Etiqueta creada con éxito");
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('admin.tags.edit', [
            'tag' => $tag,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        $this->validate($request, [
            'name' => [ 
                'required',
                Rule::unique('tags')->ignore($tag->id)
            ]
        ]);

        $tag->update($request->all());

        return redirect()->route('admin.tags.edit', $tag)->withFlash('Etiqueta actualizada con éxito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();

        return back()->withFlash('Etiqueta eliminada con éxito');
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Tag;
use Illuminate\Http\Request;

class TagsController extends Controller
{
    public function show(Tag $tag){
    	return view('home', [
    		'title' => $tag->name,
    		'posts' => $tag->posts()->paginate(),
    		'categories' => Category::all(),
    		'tags' => Tag::all(),
    	]);
    }
}

resources/views/admin/tags/create.blade.php
@extends('admin.layouts.layout')

@section('content')
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					Crear Etiqueta
				</h3>
			</div>

			<div class="box-body">
				<form method="POST" action="{{ route('admin.tags.store') }}">
					{{ csrf_field() }}
					
					<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }} ">
						<label for="name">Nombre:</label>
						<input type="text" name="name" class="form-control" value="{{ old('name') }}">

						<span class="help-block">{{ $errors->first('name') }}</span>
						
					</div>

					<div class="form-group">
						<button class="btn btn-primary btn-flat form-control">
							Crear Etiqueta
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layouts.layout')

@section('content')
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					Actualizar Etiqueta {{ $tag->name }}
				</h3>
			</div>

			<div class="box-body">
				<form method="POST" action="{{ route('admin.tags.update', $tag) }}">
					{{ csrf_field() }} {{ method_field('PUT') }}
					
					<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }} ">
						<label for="name">Nombre:</label>
						<input type="text" name="name" class="form-control" value="{{ old('name', $tag->name) }}">

						<span class="help-block">{{ $errors->first('name') }}</span>
						
					</div>

					<div class="form-group">
						<button class="btn btn-primary btn-flat form-control">
							Actualizar Categoría
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/tags/index.blade.php
@extends('admin.layouts.layout')
@section('content')
<div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title">Listado de Etiquetas</h3>
      <a class="btn btn-primary pull-right" href="{{ route('admin.tags.create') }}">
        <i class="fa fa-plus"></i> Crear Etiqueta
      </a>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <table id="tags-table" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>ID</th>
          <th>Nombre</th>
          <th>Número de entradas</th>
          <th>Acciones</th>
        </tr>
        </thead>
		
		<tbody>
			@foreach ($tags as $tag)
				<tr>
					<td>{{ $tag->id }}</td>
					<td>{{ $tag->name }}</td>
					<td>{{ $tag->posts->count() }}</td>
					<td>
            <a target="_black" href="{{ route('tags.show', $tag) }}" class="btn btn-xs btn-default"><i class="fa fa-eye" ></i></a>
						<a href="{{ route('admin.tags.edit', $tag) }}" class="btn btn-xs btn-success"><i class="fa fa-pencil"></i></a>

            <form action="{{ route('admin.tags.destroy', $tag) }}" style="display: inline" method="POST">
              {{ csrf_field() }} {{ method_field('DELETE') }}

              <button  class="btn btn-xs btn-danger"
                onclick="return confirm('¿Estás seguro que deseas eliminar esta etiqueta?');">
              <i class="fa fa-times"></i>
            </button>
            </form>
					</td>
				</tr>
			@endforeach
		</tbody>
      </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->

  @push('styles')
  	<link rel="stylesheet" href="/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
  @endpush

  @push('scripts')
  
  	<script src="/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
	<script src="/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

     <script>
	  $(function () {
	    $('#tags-table').DataTable({
	      'paging'      : true,
	      'lengthChange': true,
	      'searching'   : true,
	      'ordering'    : true,
	      'info'        : true,
	      'autoWidth'   : false
	    })
	  })
	</script>


  
  @endpush
@endsection